config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root "restaurants#index"

  resources :restaurants do
    resources :reviews
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	
  belongs_to :user
  has_many :reviews,
      -> { extending WithUserAssociationExtension }, dependent: :destroy
	validates :name, length: { minimum: 3 }, uniqueness: true

  # has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  # validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  # attr_accessible :picture
  mount_uploader :picture, PictureUploader

	def average_rating
		return 'N/A' if reviews.none?
		reviews.average(:rating)
		# reviews.sum(:rating) / reviews.count
	end

  def created_by?(current_user)
    user == current_user
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :user
	validates :rating, inclusion: (1..5)
	validates :thoughts, presence: true
	validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :restaurants
	has_many :reviews
	has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    # user.name = auth.info.name   # assuming the user model has a name
	    # user.image = auth.info.image # assuming the user model has an image
	  end
	end

	def has_reviewed?(restaurant)
	  reviewed_restaurants.include? restaurant
	end
	
end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension
  def create_with_user(attributes = {}, user)
   attributes[:user] ||= user
   create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  
	# Utility methods
	def restaurant_params
    params.require(:restaurant).permit(:name, :description, :picture)
  end
	
	# GET
	def index
		@restaurants = Restaurant.all.sort_by{ |r| r.name }
  end

  # GET
  def new
  	@restaurant = Restaurant.new
  end

  # POST
  def create
  	@restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to '/restaurants'
    else
      render 'new'
    end
  end

  # GET
  # This method gets called when you go to /restaurants/:restaurant_id, and uses the ID passed in the URL to look up the correct record from the database.
  def show
  	@restaurant = Restaurant.find(params[:id])
  end

  # GET
  def edit
  	@restaurant = Restaurant.find(params[:id])
  end

  # PATCH
  def update
  	@restaurant = Restaurant.find(params[:id])
  	@restaurant.update(restaurant_params)

  	redirect_to '/restaurants'
  end

  # DELETE/DESTROY
  def destroy
  	@restaurant = Restaurant.find(params[:id])
  	@restaurant.destroy
  	flash[:notice] = "Restaurant deleted succesfully"
  	
  	redirect_to '/restaurants'
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :authenticate_user!

  # Utility methods
	def review_params
  	params.require(:review).permit(:thoughts, :rating)
  end

	def new
  	@restaurant = Restaurant.find(params[:restaurant_id])
  	@review = Review.new
  end

  def create
  	@restaurant = Restaurant.find(params[:restaurant_id])
  	@review = @restaurant.reviews.build_with_user(review_params, current_user)

    if @review.save
      redirect_to '/restaurants'
    else
      flash.now[:notice] = "Field cannot be blank"
      render 'new'
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to root_path
    end
  end

  def failure
    redirect_to root_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
	<ul><li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li></ul>
<% else %>
	<ul>
		<li><%= link_to 'Sign in', new_user_session_path %></li>
		<li><%= link_to 'Sign up', new_user_registration_path %></li>
		<li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
	</ul>
<% end %>
<%= notice %>
<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, html: {multipart: true} do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :description %><br>
  <%= f.text_field :description %><br>
  <%= f.file_field :picture %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form" %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
    <h2><%= link_to restaurant.name, restaurant_path(restaurant), :class => "restaurant_name" %></h2>
    <% unless restaurant.picture_url.nil? %>
      <%= image_tag restaurant.picture_url(:thumbnail) %><br>
    <% end %>
    <%if user_signed_in? %>
      <p>
      <span><%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %> - </span>
      <span><%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %></span>
      <% unless current_user.has_reviewed?(restaurant) %>
        <span> - <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %></span>
      <% end %>
      </p>
    <% end %>
    
    <% if restaurant.reviews.any? %>
    	<h3>Average rating: <%= restaurant.average_rating.to_i %></h3>
		  <ul>
		  <% restaurant.reviews.each do |r| %>
		    <li><%= r.thoughts %></li>
		  <% end %>
		  </ul>
		<% else %>
			<p>No reviews for <%= restaurant.name %> yet.</p>
		<% end %>	
  <% end %>
<% else %>
  <h1>No restaurants yet</h1>
<% end %>

<a href="/restaurants/new">Add a restaurant</a>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
	<section id='errors'>
		<h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>
		<ul>
			<% @restaurant.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</section>
	<br>
<% end %>

<%= render "form" %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.description %></p>
<%= image_tag @restaurant.picture_url(:display) %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %>
  <%= f.submit 'Leave Review' %>
<% end %>